{
 "title": "DSL Modem Tracker",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Download Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "dsl_modem_downstreamCurrRate",
     "legendFormat": "Download without Attenuation Rate"
    },
    { "expr": "dsl_modem_downstreamMaxRate", "legendFormat": "Download Max Rate" },
    {
     "expr": "dsl_modem_downstreamCurrRate - dsl_modem_downstreamAttenuation",
     "legendFormat": "Download Current Rate"
    }
   ]
  },
  {
   "title": "SNR Margin",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "dsl_modem_downstreamNoiseMargin / 10",
     "legendFormat": "Noise"
    }
   ]
  },
  {
   "title": "Upload Speed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "dsl_modem_upstreamCurrRate",
     "legendFormat": "Upload without Attenuation Rate"
    },
    { "expr": "dsl_modem_upstreamMaxRate", "legendFormat": "Upload Max Rate" },
    {
     "expr": "dsl_modem_upstreamCurrRate - dsl_modem_upstreamAttenuation",
     "legendFormat": "Upload Current Rate"
    }
   ]
  },
  {
   "title": "Line Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "dsl_modem_status == 1 OR dsl_modem_status == 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}